Scheduler date/time format issue with localized sites.
dnnsoftware/Dnn.AdminExperience pull request #287
Opened 2019-01-02 10:36 UTC by mean2me

This pull request fixes a bug with localized sites and Schedulers. 
When using a Locale like (for example) ES or IT, dates coming from TaskSchedulerController are breaking our DatePicker component. 
I also cleaned up React code a bit. 

As a next step, in a separate pull request, we should format DatePicker value according to current site's Locale.

2019-01-02 11:56 UTC, daguiler requested changes
Build is breaking with
```
D:\a\1\s\Extensions\Settings\Dnn.PersonaBar.TaskScheduler\TaskScheduler.Web\src\components\scheduler\schedulerEditor\index.jsx
##[error]279(0,0): Error : JSX attributes must only be assigned a non-empty expression
```
Also please apply suggestion.

2019-01-02 11:56 UTC, daguiler commented on Extensions/Settings/Dnn.PersonaBar.TaskScheduler/TaskScheduler.Web/src/components/scheduler/schedulerEditor/index.jsx
> +                    CIAO
```suggestion
```

2019-01-04 21:25 UTC, valadas commented
I am not able to reproduce the original issue on 9.3.0.106 , I tried adding fr-ca, es-es, it-it. I switched to each of those languages on the site before using the scheduler module, I tried setting the user preferred locale to each. In all cases the calendar in the scheduler was working.

 @mean2me  Could you provide steps to reproduce please.

2019-01-06 02:21 UTC, daguiler commented
Here's how I reproduced on 9.3.0-alpha.103.7992:
1) Specified a DD/MM/YYYY locale (es-ES) as the default of the site
2) Opened Scheduler and saw all dates were displayed correctly in DD/MM/YYYY format
3) I created a test task, leaving start date null
4) Clicked on Edit Task icon. No issues, I was able to edit the newly created task, BUT datepicker showed English format (MM/DD/YYYY). This didn't happen in 9.2.2.
5) I specified 12/12/2018 as start date. Saved. Tried to edit again. No issues.
6) Then I specified 12/**13**/2018. Saved. Tried to edit again. This time, the screen went blank and got several javascript errors in the browser console:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.t.getWeekArray (export-bundle.js?cdv=52:12)
    at t.value (export-bundle.js?cdv=52:98)
    at ua (export-bundle.js?cdv=52:90)
    at la (export-bundle.js?cdv=52:90)
    at pa (export-bundle.js?cdv=52:90)
    at qa (export-bundle.js?cdv=52:90)
    at Qa (export-bundle.js?cdv=52:90)
    at xi (export-bundle.js?cdv=52:90)
    at Pi (export-bundle.js?cdv=52:90)
    at Di (export-bundle.js?cdv=52:90)
```
Error occurs at /DesktopModules/admin/Dnn.PersonaBar/scripts/exports/export-bundle.js?cdv=52

2019-01-06 02:47 UTC, valadas commented
Thank you, I was missing the default site language part. I will re-review tonight.

2019-01-06 16:59 UTC, daguiler commented on Extensions/Settings/Dnn.PersonaBar.TaskScheduler/TaskScheduler.Web/src/components/scheduler/schedulerEditor/index.jsx
> +                        mode={}
This line is generating error
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\a\1\s\Extensions\Settings\Dnn.PersonaBar.TaskScheduler\TaskScheduler.Web\src\components\scheduler\schedulerEditor\index.jsx:
JSX attributes must only be assigned a non-empty expression (279:29)

  277 |                     <DatePicker
  278 |                         date={this.getValue("ScheduleStartDate")}
> 279 |                         mode={}
      |                              ^
  280 |                         updateDate={this.onSettingChange.bind(this, "ScheduleStartDate")}
  281 |                         isDateRange={false}
  282 |                         hasTimePicker={true}
```

2019-01-06 22:56 UTC, valadas commented
I added 2 commits that address the build issue and one build warning, tested locally and it looks good to me, but the CI did not fire with my commits, not sure why?...

2019-01-06 22:57 UTC, valadas approved these changes
Tested locally, fixes the issue and cleans up the code, I added 2 commits to fix the build error and one build warning. Other than that, looks good to me.

2019-01-06 23:58 UTC, daguiler approved these changes
Thanks @valadas!

2019-01-07 00:00 UTC, merged

2019-01-07 00:01 UTC, valadas commented
You are welcome @daguiler